export default {
  a_step: {
    es: `

El **PFSA (Puntos de Función Sin Ajustar)** es una métrica utilizada en la estimación de software para medir el tamaño funcional de un sistema sin considerar factores de ajuste. Se calcula identificando las funciones del sistema y asignando un peso según su complejidad.

Para calcular el PFSA necesitamos:

### 1. Identificar las funciones del sistema

-   **Entradas Externas (EI)**: Datos que ingresan al sistema desde el usuario o sistemas externos.
-   **Salidas Externas (EO)**: Información que el sistema genera y envía al usuario o sistemas externos.
-   **Consultas Externas (EQ)**: Interacciones que permiten al usuario obtener información específica.
-   **Ficheros Lógicos Internos (ILF)**: Bases de datos o archivos gestionados por el sistema.
-   **Ficheros Lógicos Externos (ELF)**: Bases de datos o archivos gestionados por sistemas externos pero utilizados por el sistema.

### 2. Asignar complejidad

-   Cada función se clasifica como de **baja**, **media** o **alta complejidad**, según criterios como el número de campos o el nivel de interacción.

### 3. Asignar pesos

-   Utiliza una tabla estándar (como la del IFPUG) para asignar un peso numérico a cada función según su tipo y complejidad.

### 4. Sumar los valores

-   Calcula el total de puntos sumando los valores asignados a todas las funciones.
`,
    en: `**Unadjusted Function Points (UFP)** is a metric used in software estimation to measure the functional size of a system without considering adjustment factors. It is calculated by identifying system functions and assigning a weight based on their complexity.

To calculate UFP we need:

### **1. Identify system functions**

- **External Inputs (EI):** Data that enters the system from users or external systems.
- **External Outputs (EO):** Information generated by the system and sent to users or external systems.
- **External Queries (EQ):** Interactions that allow users to retrieve specific information.
- **Internal Logical Files (ILF):** Databases or files managed by the system.
- **External Logical Files (ELF):** Databases or files managed by external systems but used by the system.

### **2. Assign complexity**

- Each function is classified as **low**, **medium**, or **high complexity**, based on criteria like the number of fields or the level of interaction.

### **3. Assign weights**

- Use a standard table (such as the IFPUG table) to assign a numerical weight to each function based on its type and complexity.

### **4. Sum the values**

- Calculate the total points by summing the values assigned to all functions.
    `,
  },
  b_step: {
    es: `El **PFA (Puntos de Función Ajustados)** es una métrica utilizada en la estimación de software que ajusta los **Puntos de Función Sin Ajustar (PFSA)** según factores de complejidad del sistema. Se calcula siguiendo estos pasos:

### **1. Calcular los PFSA**

- Identifica las funciones del sistema:
    - **Entradas Externas (EI):** Datos que ingresan al sistema desde el usuario o sistemas externos.
    - **Salidas Externas (EO):** Información que el sistema genera y envía al usuario o sistemas externos.
    - **Consultas Externas (EQ):** Interacciones que permiten al usuario obtener información específica.
    - **Ficheros Lógicos Internos (ILF):** Bases de datos o archivos gestionados por el sistema.
    - **Ficheros Lógicos Externos (ELF):** Bases de datos o archivos gestionados por sistemas externos pero utilizados por el sistema.
- Asigna un peso a cada función según su complejidad (baja, media, alta).
- Suma los valores para obtener el **PFSA**.

### **2. Identificar los Factores de Ajuste**

- Existen **14 factores de ajuste** que afectan la complejidad del sistema, entre estos tenemos:
    - **Comunicación de datos**: ¿El sistema intercambia datos con otros sistemas?
    - **Distribución de datos**: ¿Los datos están distribuidos en múltiples ubicaciones?
    - **Complejidad de procesamiento**: ¿El sistema realiza cálculos complejos o procesamiento intensivo?
    - **Reutilización del código**: ¿Se reutilizan componentes de software?
    - **Facilidad de instalación**: ¿El sistema es fácil de instalar en diferentes entornos?
    - **Facilidad de operación**: ¿El sistema es intuitivo y fácil de usar?
    - **Portabilidad**: ¿El software puede ejecutarse en múltiples plataformas?
    - **Mantenimiento**: ¿Es fácil modificar y actualizar el sistema?
    - **Rendimiento**: ¿El sistema tiene requisitos de alto rendimiento?
    - **Uso concurrente**: ¿Múltiples usuarios pueden acceder simultáneamente?
    - **Seguridad**: ¿El sistema tiene requisitos estrictos de seguridad?
    - **Acceso directo**: ¿El sistema permite acceso directo a bases de datos?
    - **Entradas múltiples**: ¿El sistema recibe datos de múltiples fuentes?
    - **Facilidad de cambios**: ¿El sistema permite modificaciones sin afectar su estabilidad?

### **3. Calcular el Valor de Ajuste**

- Para cada factor de ajuste, asigna un valor entre **0 (sin influencia)** y **5 (influencia muy alta)**.
- Suma los valores asignados a los 14 factores (_ΣFi_).

### **4. Aplicar la Fórmula de Ajuste**

- Usa la siguiente fórmula:
\n$AFP=UFP×(0.65+0.01×ΣFi)AFP=UFP×(0.65+0.01×ΣFi)$

- Donde:
    - _ΣFi_ es la suma de los valores de los factores de ajuste.
    - 0.650.65 y 0.010.01 son constantes definidas por el método.`,
    en: `
The **Adjusted Function Points (AFP)** is a metric used in software estimation that modifies the **Unadjusted Function Points (UFP)** according to system complexity factors. It is calculated following these steps:
### **1. Calculate UFP**
-   Identify the system functions:
    -   **External Inputs (EI):** Data that enters the system from users or external systems.
    -   **External Outputs (EO):** Information generated by the system and sent to users or external systems.
    -   **External Queries (EQ):** Interactions that allow users to retrieve specific information.
    -   **Internal Logical Files (ILF):** Databases or files managed by the system.
    -   **External Logical Files (ELF):** Databases or files managed by external systems but used by the system.
-   Assign a weight to each function based on its complexity (low, medium, high).
-   Sum the values to obtain the **UFP**.
### **2. Identify Adjustment Factors**
-   There are **14 standard adjustment factors** that affect system complexity, including:
    -   **Data communication:** Does the system exchange data with other systems?
    -   **Data distribution:** Are data distributed across multiple locations?
    -   **Processing complexity:** Does the system perform complex calculations or intensive processing?
    -   **Code reuse:** Are software components reused?
    -   **Ease of installation:** Is the system easy to install in different environments?
    -   **Ease of operation:** Is the system intuitive and easy to use?
    -   **Portability:** Can the software run on multiple platforms?
    -   **Maintainability:** Is the system easy to modify and update?
    -   **Performance:** Does the system have high-performance requirements?
    -   **Concurrency:** Can multiple users access the system simultaneously?
    -   **Security:** Does the system have strict security requirements?
    -   **Direct access:** Does the system allow direct access to databases?
    -   **Multiple inputs:** Does the system receive data from multiple sources?
    -   **Ease of change:** Can modifications be made without affecting system stability?
### **3. Calculate the Adjustment Value**
-   Assign a value between **0 (no influence)** and **5 (very high influence)** to each adjustment factor.
-   Sum the values assigned to all 14 factors (_ΣFi_).
### **4. Apply the Adjustment Formula**
-   Use the following formula:
\n$AFP=UFP×(0.65+0.01×ΣFi)$
-   Where:
    -   _ΣFi_ is the sum of the adjustment factor values.
    -   **0.65** and **0.01** are constants defined by the method.`,
  },
  c_step: {
    es: `La **conversión de Puntos de Función (PF) a Líneas de Código (LDC)** es un método utilizado en la estimación de software para traducir la funcionalidad medida en puntos de función a una cantidad aproximada de líneas de código necesarias para implementar esa funcionalidad.

### **Cómo calcular la conversión de PF a LDC**

1. **Determinar los Puntos de Función Ajustados (PFA)**
    - Calcula los **Puntos de Función Sin Ajustar (PFSA)** y aplica los factores de ajuste para obtener los **PFA**.
2. **Consultar la tabla de conversión**
    - Cada lenguaje de programación tiene un promedio de líneas de código por punto de función. Por ejemplo:
        - Java: **53 LDC por PF**
        - Python: **28 LDC por PF**
        - TypeScript: **50 LDC por PF**
3. **Aplicar la fórmula de conversión**
    - Multiplica los **PFA** por el factor de conversión del lenguaje de programación:
    \n
    $LOC=PFAxFactor de conversión$`,
    en: `The **conversion of Function Points (FP) to Lines of Code (LOC)** is a method used in software estimation to translate functionality measured in function points into an approximate number of lines of code needed to implement that functionality.

### **How to Calculate FP to LOC Conversion**

1. **Determine the Adjusted Function Points (AFP)**
    - Calculate the **Unadjusted Function Points (UFP)** and apply the adjustment factors to obtain the **AFP**.
2. **Refer to the conversion table**
    - Each programming language has an average number of lines of code per function point. For example:
        - Java: **53 LOC per FP**
        - Python: **28 LOC per FP**
        - TypeScript: **50 LOC per FP**
3. **Apply the conversion formula**
    - Multiply the **AFP** by the conversion factor of the programming language:
    \n
    $$LOC=AFP×ConversionFactor$$`,
  },
  d_step: {
    es: `Para aplicar COCOMO, se siguen estos pasos:

### Determinación del FAE

El **Factor de Ajuste del Esfuerzo (FAE)** se calcula considerando **14 factores de ajuste**, como la complejidad del procesamiento, la seguridad, la reutilización del código y la facilidad de mantenimiento. Dependiendo del tipo de proyecto, el FAE varía:

- **Orgánico** (simple, pequeño, con requisitos bien definidos): **FAE ≈ 0.9 - 1.1**.
- **Semiacoplado** (moderada complejidad, requisitos cambiantes): **FAE ≈ 1.0 - 1.3**.
- **Empotrado** (alta complejidad, restricciones estrictas): **FAE ≈ 1.2 - 1.5**.

El FAE se obtiene multiplicando los valores asignados a cada factor de ajuste.

### Cálculo del esfuerzo (persona-meses)

Se usa la fórmula:

$$
E=a×(KLDC)^b
$$

Donde **a** y **b** son constantes del modelo (dependiendo del tipo de proyecto) y **KLDC** son las miles de líneas de código entregadas.

### Cálculo del tiempo de desarrollo (meses)

Se usa la fórmula:

$$
T=c×(Esfuerzo)^d
$$

Donde **T** es el tiempo estimado en **meses** y **c**, **d** son las constantes del modelo (dependiendo del tipo de proyecto).

### Cálculo del número de personas

Se obtiene dividiendo el esfuerzo entre el tiempo estimado:
$$
y = {E \\over T}
$$`,
    en: `Applying COCOMO:

### **Determining the Effort Adjustment Factor (FAE)**

The **Effort Adjustment Factor (FAE)** is calculated based on **14 adjustment factors**, such as processing complexity, security, code reuse, and maintainability. Depending on the type of project, the FAE varies:

- **Organic** (simple, small, with well-defined requirements): **FAE ≈ 0.9 - 1.1**.
- **Semi-detached** (moderate complexity, evolving requirements): **FAE ≈ 1.0 - 1.3**.
- **Embedded** (high complexity, strict constraints): **FAE ≈ 1.2 - 1.5**.

The FAE is obtained by multiplying the values assigned to each adjustment factor.

### **Calculating Effort (Person-Months)**

The formula used is:

$$
E=a×(KLDC)^b
$$

Where:

- **a** and **b** are model constants (depending on the project type).
- **KLDC** represents thousands of delivered lines of code.

### **Calculating Development Time (Months)**

The formula used is:

$$
T=c×(Effort)^d
$$

Where:

- **T** is the estimated time in **months**.
- **c** and **d** are model constants (depending on the project type).

### **Calculating the Number of People**

The number of required personnel is determined by dividing the effort by the estimated time:

$$
y = {E \\over T}
$$`,
  },
  e_step: {
    es: `El **costo de desarrollo** es el gasto total necesario para diseñar, construir y entregar un producto o sistema de software. Incluye factores como salarios del equipo, herramientas, infraestructura, pruebas y mantenimiento.

Para calcular el costo de desarrollo por mes debemos multiplicar el número de personas ‘**P**’ por el tiempo de desarrollo (**T**) en conjunto con el sueldo medio de un desarrollador por mes (**500$**):

$$
CD=P*T*500
$$`,
    en: `The development cost is the total expense required to design, build, and deliver a software product or system. It includes factors such as team salaries, tools, infrastructure, testing, and maintenance.

To calculate the monthly development cost, we must multiply the number of people 'P' by the development time 'T', along with the average salary of a developer per month ($500):
$$
DC=P*T*500
$$`,
  },
}
